/** Tailwind config — Design System exacto de Stitch (DESIGN_SYSTEM_4)
 *  Tokens tomados del export home_versi_n_refinada_champagne/code.html
 *  Esto es lo que hace que el render sea PIXEL-IDÉNTICO a Stitch.
 */
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#0B1528",
        "surface-dim": "#d9dadb",
        "tertiary-fixed-dim": "#E0CB99",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#6E5525",
        "secondary-fixed": "#F2E8D5",
        secondary: "#B89758",
        "on-secondary-fixed": "#3A2E14",
        "surface-variant": "#e1e3e4",
        "on-error-container": "#93000a",
        "outline-variant": "#c5c6ce",
        "secondary-fixed-dim": "#E0CB99",
        "on-background": "#191c1d",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1d",
        surface: "#FAF9F6",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#6E5525",
        "on-secondary-container": "#6E5525",
        "tertiary-fixed": "#F2E8D5",
        "tertiary-container": "#3A2E14",
        "surface-container": "#edeeef",
        "on-secondary": "#ffffff",
        "inverse-primary": "#b9c6e9",
        "on-tertiary-container": "#B89758",
        "on-primary-fixed-variant": "#394763",
        "surface-container-low": "#f3f4f5",
        "inverse-on-surface": "#f0f1f2",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#3A2E14",
        "inverse-surface": "#2e3132",
        "surface-bright": "#FAF9F6",
        "error-container": "#ffdad6",
        tertiary: "#334155",
        "secondary-container": "#F5EEDF",
        background: "#FAF9F6",
        "primary-fixed": "#d8e2ff",
        outline: "#75777e",
        "primary-container": "#0c1b35",
        "surface-container-highest": "#e1e3e4",
        error: "#ba1a1a",
        "on-surface-variant": "#45474d",
        "surface-tint": "#515e7c",
        "surface-container-high": "#e7e8e9",
        "on-primary-fixed": "#0c1b35",
        "primary-fixed-dim": "#b9c6e9",
        "link-gold": "#8A6B2E",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        base: "8px",
        "margin-desktop": "64px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-md": ["var(--font-serif)", "Georgia", "serif"],
        "display-lg": ["var(--font-serif)", "Georgia", "serif"],
        "headline-sm": ["var(--font-serif)", "Georgia", "serif"],
        "display-lg-mobile": ["var(--font-serif)", "Georgia", "serif"],
        "label-caps": ["var(--font-sans)", "system-ui", "sans-serif"],
        "body-md": ["var(--font-sans)", "system-ui", "sans-serif"],
        "body-lg": ["var(--font-sans)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
